-- CreateTable
CREATE TABLE `TRANSACTIONS` (
    `IDTRANSACTIONS` INTEGER NOT NULL AUTO_INCREMENT,
    `IDUSUARIO` INTEGER NOT NULL,
    `VALOR` DOUBLE NOT NULL,
    `NOME` VARCHAR(191) NOT NULL,
    `DESCRICAO` VARCHAR(191) NOT NULL,
    `TIPO` VARCHAR(191) NOT NULL,
    `DTCRIACAO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DTEDICAO` DATETIME(3) NULL,
    `DTDELETE` DATETIME(3) NULL,

    PRIMARY KEY (`IDTRANSACTIONS`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TRANSACTIONS` ADD CONSTRAINT `TRANSACTIONS_IDUSUARIO_fkey` FOREIGN KEY (`IDUSUARIO`) REFERENCES `USUARIO`(`IDUSUARIO`) ON DELETE RESTRICT ON UPDATE CASCADE;
