-- CreateTable
CREATE TABLE `USUARIO` (
    `IDUSUARIO` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(191) NOT NULL,
    `SENHA` VARCHAR(191) NOT NULL,
    `EMAIL` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `USUARIO_EMAIL_key`(`EMAIL`),
    PRIMARY KEY (`IDUSUARIO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TOKEN` (
    `IDTOKEN` INTEGER NOT NULL AUTO_INCREMENT,
    `TOKEN` VARCHAR(191) NOT NULL,
    `DTCRIACAO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DTEXPIRA` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `IDUSUARIO` INTEGER NOT NULL,

    PRIMARY KEY (`IDTOKEN`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `INVESTIMENTO` (
    `IDINVESTIMENTO` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(191) NOT NULL,
    `VALOR` DOUBLE NOT NULL,
    `PRECOMEDIO` DOUBLE NOT NULL,
    `CATEGORIAS` VARCHAR(191) NOT NULL,
    `DTCRIACAO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DTUPDATE` DATETIME(3) NULL,
    `DTDELETE` DATETIME(3) NULL,
    `QUANTIDADE` INTEGER NOT NULL,
    `IDUSUARIO` INTEGER NOT NULL,

    PRIMARY KEY (`IDINVESTIMENTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROFIT` (
    `IDPROFIT` INTEGER NOT NULL AUTO_INCREMENT,
    `DTCRIACAO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `VALOR` DOUBLE NOT NULL,
    `DESCRICAO` VARCHAR(191) NOT NULL,
    `TPPROFIT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `IDCATEGORIA` INTEGER NOT NULL,
    `IDINVESTIMENTO` INTEGER NOT NULL,

    PRIMARY KEY (`IDPROFIT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CATEGORIA` (
    `IDCATEGORIA` INTEGER NOT NULL AUTO_INCREMENT,
    `DESCRICAO` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`IDCATEGORIA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TOKEN` ADD CONSTRAINT `TOKEN_IDUSUARIO_fkey` FOREIGN KEY (`IDUSUARIO`) REFERENCES `USUARIO`(`IDUSUARIO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INVESTIMENTO` ADD CONSTRAINT `INVESTIMENTO_IDUSUARIO_fkey` FOREIGN KEY (`IDUSUARIO`) REFERENCES `USUARIO`(`IDUSUARIO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROFIT` ADD CONSTRAINT `PROFIT_IDCATEGORIA_fkey` FOREIGN KEY (`IDCATEGORIA`) REFERENCES `CATEGORIA`(`IDCATEGORIA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROFIT` ADD CONSTRAINT `PROFIT_IDINVESTIMENTO_fkey` FOREIGN KEY (`IDINVESTIMENTO`) REFERENCES `INVESTIMENTO`(`IDINVESTIMENTO`) ON DELETE RESTRICT ON UPDATE CASCADE;
